name: sekolah_asisi
description: Sekolah Asisi Attendance App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.0
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.0
  shimmer: ^3.0.0
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/SMK Asisi.png
